name: DEPLOY TO STAGING

on:
    pull_request:
        types: [closed]
        branches:
            - develop

jobs:
    aws-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: develop
            - uses: actions/setup-node@v1
            - run: npm install
            - run: npm run build
            - run: npm run bundle
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: 'deploy/'
                  REMOTE_HOST: 'todo.eaglesoftwareteam.com'
                  REMOTE_USER: ubuntu
                  TARGET: 'nodeapps/todo-backend'
            - name: Execute SSH commmands on remote server
              uses: JimCronqvist/action-ssh@master
              env:
                  NAME: 'Root'
              with:
                  hosts: 'ubuntu@todo.eaglesoftwareteam.com'
                  privateKey: ${{ secrets.SERVER_SSH_KEY }}
                  debug: false
                  command: |
                      cd nodeapps/todo-backend
                      npm install
                      sudo systemctl stop todo-backend
                      sudo cp /home/ubuntu/nodeapps/todo-backend/todo-backend.service /lib/systemd/system/todo-backend.service
                      sudo systemctl start todo-backend
